
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("user/new", "Create user")) ?>
</div>

<?php echo $this->tag->form(array("user/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search user</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="first_name">First Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("first_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_name">Last Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="attribute_id">Attribute</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("attribute_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
